language: node_js

node_js:
  - 'node'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint
  - yarn test
  - yarn build
